title: Wayne Kimani | Financial Analyst & Software Engineer
description: Financial Analyst and Software Engineer. Specializing in financial systems design, data analysis, and full-stack development.
url: https://that-kimani.github.io/portfolio-website